name: Run pre-commit

on:
  push:
    branches-ignore:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: cicirello/pyaction:4.29
    steps:
      - uses: actions/checkout@v4
        with:
          path: folder
      - run: cd folder
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: |
          cd folder/ \
          && pre-commit run --color=always --all-files
